/**
 * Phase 0 smoke test: the fixtures that Phase 1 parses are present and well-formed.
 * They are copies of ./data/, regenerated by reference/probe_*.py — see CLAUDE.md.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const fixture = (name: string) => readFileSync(join(import.meta.dirname, "fixtures", name), "utf8");

describe("fixtures", () => {
  it("ttviewer.json lists timetables with a default", () => {
    const data = JSON.parse(fixture("ttviewer.json")) as Record<string, unknown>;
    expect(data).not.toHaveProperty("e"); // EduPage errors arrive as HTTP 200 + { e }
    expect(JSON.stringify(data)).toContain("1175");
  });

  it("regulartt_1175.json carries the aSc table map", () => {
    const data = JSON.parse(fixture("regulartt_1175.json")) as Record<string, unknown>;
    expect(data).not.toHaveProperty("e");
    for (const table of ["classes", "subjects", "teachers", "lessons", "cards", "periods"]) {
      expect(JSON.stringify(data)).toContain(`"${table}"`);
    }
  });

  it("the substitution fixture is renderable HTML", () => {
    const html = fixture("subst_2026-09-09_classes.html");
    const doc = new DOMParser().parseFromString(html, "text/html");
    expect(doc.querySelectorAll(".info").length).toBeGreaterThan(0);
  });
});
