/**
 * Smoke test: the fixtures that the parsers are built against are present and well-formed.
 * They live in repo-root `data/`, regenerated by reference/probe_*.py — see CLAUDE.md.
 */
import { describe, expect, it } from "vitest";
import { FIXTURES, readFixture, readJsonFixture } from "./fixtures.ts";

describe("fixtures", () => {
  it("ttviewer.json lists timetables with a default", () => {
    const data = readJsonFixture<Record<string, unknown>>(FIXTURES.ttviewer);
    expect(data).not.toHaveProperty("e"); // EduPage errors arrive as HTTP 200 + { e }
    expect(JSON.stringify(data)).toContain("1175");
  });

  it("regulartt_1175.json carries the aSc table map", () => {
    const data = readJsonFixture<Record<string, unknown>>(FIXTURES.regulartt);
    expect(data).not.toHaveProperty("e");
    for (const table of ["classes", "subjects", "teachers", "lessons", "cards", "periods"]) {
      expect(JSON.stringify(data)).toContain(`"${table}"`);
    }
  });

  it("the substitution fixture is renderable HTML", () => {
    const html = readFixture(FIXTURES.substHtml);
    const doc = new DOMParser().parseFromString(html, "text/html");
    expect(doc.querySelectorAll(".info").length).toBeGreaterThan(0);
  });
});
