/*
 * Build config for the landing page — a separate Vite project from the app on purpose: the app's
 * `dist/` is copied into the Android APK and precached by its service worker (03b F9), and the
 * landing must be neither. Output goes to `landing/dist`, deployed as its own Cloudflare Pages
 * project. The pages themselves are generated by `build/pages.ts`.
 */
import { fileURLToPath } from "node:url";
import { defineConfig } from "vite";
import { dsDark } from "./build/ds-dark.ts";
import { inlineCss } from "./build/inline-css.ts";
import { landingPages } from "./build/pages.ts";

const here = (path: string): string => fileURLToPath(new URL(path, import.meta.url));

export default defineConfig({
  root: here("./src"),
  publicDir: here("./public"),
  css: { postcss: { plugins: [dsDark(here("../src/ds/tokens/dark.css"))] } },
  plugins: [
    landingPages({
      srcRoot: here("./src"),
      publicDir: here("./public"),
      repoRoot: here(".."),
    }),
    inlineCss(),
  ],
  build: {
    outDir: here("./dist"),
    emptyOutDir: true,
    target: "es2019",
    cssTarget: "chrome80",
    assetsInlineLimit: 0,
    modulePreload: false,
  },
  server: {
    host: true,
    // The design tokens live outside the Vite root, in the app's `src/ds`.
    fs: { allow: [here("..")] },
  },
});
